project_name: entra-exporter

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

dockers:
  - image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile.goreleaser
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/{{ .ProjectName }}:{{ .Version }}-arm64
    dockerfile: Dockerfile.goreleaser
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64

docker_manifests:
  - name_template: ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/{{ .ProjectName }}:{{ .Version }}-arm64
  - name_template: ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/{{ .ProjectName }}:{{ .Version }}-arm64
